spring:
  port: 8080
  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASS}
    driver-class-name: org.postgresql.Driver
    datasource:
      hikari:
        connectionTimeout: 20000
        maximumPoolSize: 5
  jpa:
    hibernate.ddl-auto: update
